services:
  ollama:
    build: .
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: on-failure

volumes:
  ollama:
